USE Movies
--SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE;
SELECT CONSTRAINT_TYPE FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS;
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS

--SELECT COLUMN_NAME
--FROM	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
--where INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.TABLE_NAME =  N'Movies';
--WHERE	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.CONSTRAINT_NAME =
--		INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME
--AND		INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_TYPE = N'PRIMARY KEY'
--AND		INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.TABLE_NAME = N'Directors';


--SELECT	COLUMN_NAME
--FROM	INFORMATION_SCHEMA.TABLE_CONSTRAINTS, INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
--WHERE	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.CONSTRAINT_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME
--AND CONSTRAINT_TYPE = N'PRIMARY KEY' 
--AND INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME = N'Directors'


--это одно и тоже только в разной записи


SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
WHERE INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.CONSTRAINT_NAME = 
(
SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_TYPE = N'PRIMARY KEY' AND TABLE_NAME = N'Movies'
)
